name: good-morning
on: 
  push:
    branches:
      - main
  jobs:
    gm:
      runs-on: ubuntu-latest
      steps: 
         - name: Say Good morning to user
           run: echo "gooddd moringgg"
         - name: Say good night to user
           run: echo "good nightt"
